site_name: dawatoma docs

theme:
  name: "material"

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md # Change the page's title to "Home"
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - Deep dive: explanation.md # Change the page's title to "Deep dive" from "Explanation"